### ISSUE TITLE
Provide numpy/scipy intro

### ISSUE THREAD

**Issue by dkirkby** [fjaviersanchez/JupyterTutorial#12]
Give an intro to numpy and scipy with links for further reading.  Ideally, this tutorial will be understandable by someone who has never used numpy before.  I think the main point for new users is that numpy provides an optimized array class that should be used instead of the built-in list() wherever possible.  Perhaps a simple example comparing the same calculation in numpy and plain python near the beginning?  This could also be an opportunity to demo %timeit.

**Comment by fjaviersanchez** [comment]
Yes, I agree. It is something important to show, especially for people that think that Python is really slow.
