### ISSUE TITLE
Choice of FITS library

### ISSUE THREAD

**Issue by dkirkby** [fjaviersanchez/JupyterTutorial#13]
Lets use `astropy.io.fits` in all of the examples (since it is included in anaconda) but mention that `fitsio` is sometimes necessary for working with large files, since it uses the compiled cfitsio library whereas astropy is pure python, but has some caveats:
- Not included with anaconda
- Requires a C compiler to install
- Does not work under windows
- Similar but not identical API to astropy

**Comment by fjaviersanchez** [comment]
Done!
