### ISSUE TITLE
`quasar_table` is defined after it is first used in the notebook

### ISSUE THREAD

**Issue by drphilmarshall** [fjaviersanchez/JupyterTutorial#16]
Looks like `quasar_table` is defined _after_ it is first used, look:

> ---
> 
> NameError                                 Traceback (most recent call last)
> <ipython-input-47-7d105a5cf2a8> in <module>()
>       9 #If we don't use the correct units...
>      10 mags_wrong = sdss.get_ab_magnitudes(flux,wave)
> ---> 11 mags_boss = np.hstack(quasar_table['PSFMAG_%d' %f][40] for f in range(0,5))
>      12 print mags
>      13 print mags_boss
> 
> /home/main/anaconda2/lib/python2.7/site-packages/numpy/core/shape_base.pyc in hstack(tup)
>     273 
>     274     """
> --> 275     arrs = [atleast_1d(_m) for _m in tup]
>     276     # As a special case, dimension 0 of 1-dimensional arrays is "horizontal"
>     277     if arrs[0].ndim == 1:
> 
> <ipython-input-47-7d105a5cf2a8> in <genexpr>((f,))
>       9 #If we don't use the correct units...
>      10 mags_wrong = sdss.get_ab_magnitudes(flux,wave)
> ---> 11 mags_boss = np.hstack(quasar_table['PSFMAG_%d' %f][40] for f in range(0,5))
>      12 print mags
>      13 print mags_boss
> 
> NameError: global name 'quasar_table' is not defined

**Comment by fjaviersanchez** [comment]
Solved! :)

**Comment by drphilmarshall** [comment]
Bravo!
