### ISSUE TITLE
Include an example of making an all-sky plot?

### ISSUE THREAD

**Issue by dkirkby** [fjaviersanchez/JupyterTutorial#7]
Could plot from a FITS file including in the repo, e.g., LSST nvisits vs (ra, dec)?  Should probably avoid using `healpy` since it is not included in anaconda.  Need to check if `basemap` is included in anaconda.

Could use this as a template: https://github.com/dkirkby/bossdata/blob/master/examples/nb/MakingSkyPlots.ipynb

**Comment by fjaviersanchez** [comment]
This is available in the latest commit [cf98270](https://github.com/fjaviersanchez/JupyterTutorial/commit/c9f8270fc87719337033849099d9db0f17d8ce77)
